apiVersion: v1
kind: Pod
metadata:
  labels:
    app: v1.0.0
  name: healthcheck1
spec:
  containers:
  - name: busybox
    image: busybox:latest
    args:
    - '/bin/sh'
    - '-c'
    - 'touch /tmp/healthy; sleep 10; rm -f /tmp/healthy; sleep 10'
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 10
